### ISSUE TITLE
Not clear if/how to fill paper-steps

### ISSUE THREAD

**Issue by nicenemo** [Collaborne/paper-stepper#2]
Hi,

i pulled the sample html from your sourcecode and guessed how to use it.
Either the component is not ready yet or some documentation is lacking.

My guess  on how to use was to put content in the paper-step elements.
Am I Wrong?

**Comment by ronnyroeller** [comment]
@nicenemo - thanks for bringing this up. You basically use the stepper as you would use [`paper-tabs`](https://elements.polymer-project.org/elements/paper-tabs): bind the `selected` property to e.g. an `iron-pages` element.
I updated the demo accordingly.

**Comment by nicenemo** [comment]
Works
