### ISSUE TITLE
Why do I need the paper-step tag?

### ISSUE THREAD

**Issue by nicenemo** [Collaborne/paper-stepper#3]
Disclaimer: polymer newbe.

Why do I need a paper-step>  tag  for every page?
Can this not be deduced from counting the immediate children from  iron-pages?
Can I do extra things on individual steps?

**Comment by ronnyroeller** [comment]
It follows the pattern of [`paper-tabs`](https://elements.polymer-project.org/elements/paper-tabs).
Right now, there is no further configuration for `<paper-step>`.
