### ISSUE TITLE
localize  or custom set Back and Next text

### ISSUE THREAD

**Issue by nicenemo** [Collaborne/paper-stepper#4]
Disclaimer: polymer newbe.

Can I localize the Back and Next tags to Dutch?
Can I set them custom, e.g. the title attribute of the previous and next div?

**Comment by ronnyroeller** [comment]
Not right now. Feel free to provide a PR if you are interested in this feature.

**Comment by ronnyroeller** [comment]
This has been implemented in version 1.0.4
https://github.com/Collaborne/paper-stepper/commit/3c7e35f43935aa5fe7f2e4ea174416ac1dfc754f
